{% set name = "ttsim-backend" %}
{% set version = "1.3.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/ttsim_backend-{{ version }}.tar.gz
  sha256: 94e4d937880100b9ec9fef6782fdea14dacb76c3e03aa20080acd688bcfc128c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - dags >=0.6
    - ipywidgets
    - python-kaleido >=1.1
    - networkx >=3.5
    - numpy_groupies
    - numpy
    - openpyxl
    - optree >=0.16.0
    - pandas >=3
    - plotly >=6.5
    - portion
    - pygments
    - pygraphviz
    - pytest
    - pyyaml

test:
  imports:
    - ttsim
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: code powering Taxes and Transfers SIMulators
  license: AGPL-3.0-only
  license_file: LICENSE
  home: https://github.com/ttsim-dev/ttsim

extra:
  recipe-maintainers:
    - hmgaudecker
    - MImmesberger
